### ISSUE TITLE
Download speed is really slow

### ISSUE THREAD

**Issue by Bibo1984** [xypwn/southpark-de-downloader#11] opened 2023-08-27 10:35 UTC
Hi the download speed is realy slow i've 100mbit connection but after 15min is only 35MB downloaded is there anyway to increrase the speed?

**Comment by xypwn** [comment] 2023-08-27 17:12
Works on my machine ¯\_(ツ)_/¯.

Seriously though, I also have 100Mbit and I can't reproduce this (~3MB/s for me).

First of all, this could just be temporary (is it still slow?).

Also, did you check whether anything running in the background might be eating up your bandwidth?

If the issue persists, you can also check if videos on https://southparkstudios.com/ play back, since your browser should be using the exact same API as this script to download the videos on the website.

Finally, you can see if maybe my [South Park Downloader GUI](https://github.com/xypwn/southpark-downloader-ui) works any better. If it's still slow for you, you can also choose to increase parallel downloads as that might increase the overall speed.

**Comment by Bibo1984** [comment] 2023-08-28 18:09
Hi, It is still realy slow. The Gui is downloading faster but there some episodes are not downloading...

**Comment by xypwn** [comment] 2023-08-28 21:30
Huh, it's definitely strange that the GUI is faster, but great if it works at least.

Which episodes are not downloading? This might be due to your region as SP services are very regional. What country are you in?

**Comment by Bibo1984** [comment] 2023-09-02 18:50
HI i'm in Germany i.e. 
This episodes are not downloading with gui: (In German)
-S1 E11 
-S2 E2,4
-S7 E1,4
-S8 E1
-S9 E4,12
-S10 E2,10
-S11 E2,3,4,5,6,7,8,9,13,14
-S12 E1,2,3,5,6,
-S13 E1,2,4,6,7,8,9,10,11,12,14
-S14 E2,3,4,7
-S16 E3
-S17 E1
-S20 E3

**Comment by xypwn** [comment] 2023-09-04 09:31
Hi, thanks for providing this comprehensive list! I'm also in Germany and could reproduce the bug. I'll try to figure out what's wrong and fix it.
~~Meanwhile, it'd be great if you could open an issue (regarding the episodes not downloading) in the South Park Downloader GUI's repo, just to keep things organized and separated.~~
EDIT: Should be fine to keep the issue here since I basically figured it out, just open a separate one on the GUI page next time :)

**Comment by xypwn** [comment] 2023-09-04 10:32
Turns out this wasn't the only issue, you should have seen an error message. I just fixed that.

**Comment by xypwn** [comment] 2023-09-04 10:35
I also found out the reason why the episodes aren't downloading. It's because the ones you specified don't have subtitles available, which my downloader sees as an error. I'll fix that too and let you know when I updated the releases (I'm not home atm where I have all the SDKs for cross compiling).

**Comment by xypwn** [comment] 2023-09-04 11:03
Alright, I just fixed that bug too. Once I update the release (when I get home), you should be able to download the new version and everything should work. Of course you can also just build from source if you don't want to wait ;) (clone the repo, download golang and run `go build ./cmd/southpark-downloader-ui`)

**Comment by Bibo1984** [comment] 2023-09-06 17:36
Hi i'm sorry for the late response. i see it's all done. the GUI is working now.  Thank you so much!

**Comment by xypwn** [comment] 2023-09-06 17:41
Hi, no problem. Glad it's working for you now!
IDK what's up with the slow download speed for the CLI script, but since I can't reproduce that I won't fix it for now.

**Closed as not planned by xypwn** 2023-09-06 17:41 UTC
Labels: bug
